// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNhjEELaRZdhI9cc3FBG1g4W7vrDEXjg0',
    appId: '1:947891423660:web:4f85b9b61574fd44c35209',
    messagingSenderId: '947891423660',
    projectId: 'my-map-project-402519',
    authDomain: 'my-map-project-402519.firebaseapp.com',
    storageBucket: 'my-map-project-402519.appspot.com',
    measurementId: 'G-D6D9CKCN1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwzsPq9YVi_aagRAJn6KFMNGCcRbnqXw',
    appId: '1:947891423660:android:dc35dcb586cdaceec35209',
    messagingSenderId: '947891423660',
    projectId: 'my-map-project-402519',
    storageBucket: 'my-map-project-402519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkOn-PdqyVSuzCofrETbsthUKhd0rEJs8',
    appId: '1:947891423660:ios:a5a90102f046d11ac35209',
    messagingSenderId: '947891423660',
    projectId: 'my-map-project-402519',
    storageBucket: 'my-map-project-402519.appspot.com',
    iosClientId: '947891423660-r22m6b420nv3mc5qotitvkoa2lkstmdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
